# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HlTickers < Formula
  desc "Fast terminal market watcher powered by Hyperliquid — no keys, no accounts"
  homepage "https://github.com/brayden967/hl-tickers"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Brayden967/hl-tickers/releases/download/v0.1.1/hl-tickers_0.1.1_darwin_amd64.tar.gz"
      sha256 "167e266e218b9fac2c9967a64ea0ec4186b5410bdfa6f45653c319ed9c69d4e4"

      define_method(:install) do
        bin.install "hl-tickers"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Brayden967/hl-tickers/releases/download/v0.1.1/hl-tickers_0.1.1_darwin_arm64.tar.gz"
      sha256 "b86ab4f5092ee204edc8fdf7c15208ee82c3546f87115cd6301b5bf21cc5060a"

      define_method(:install) do
        bin.install "hl-tickers"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Brayden967/hl-tickers/releases/download/v0.1.1/hl-tickers_0.1.1_linux_amd64.tar.gz"
      sha256 "0a633c48621f7518d004dd64bdfcbde70dba3aa16d8eda6c3568da94de5de27f"
      define_method(:install) do
        bin.install "hl-tickers"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Brayden967/hl-tickers/releases/download/v0.1.1/hl-tickers_0.1.1_linux_arm64.tar.gz"
      sha256 "9652ddfc011b096d25a86be55dca2a14b3f26125ef3a8cdbd7a2a1f3cdcce057"
      define_method(:install) do
        bin.install "hl-tickers"
      end
    end
  end

  test do
    system "#{bin}/hl-tickers", "--version"
  end
end
