# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HlTickers < Formula
  desc "Fast terminal market watcher powered by Hyperliquid — no keys, no accounts"
  homepage "https://github.com/brayden967/hl-tickers"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Brayden967/hl-tickers/releases/download/v0.1.0/hl-tickers_0.1.0_darwin_amd64.tar.gz"
      sha256 "8bb959be60d14c1b7da597004e97be50c676147f35e5dfca14ce07d932851674"

      define_method(:install) do
        bin.install "hl-tickers"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Brayden967/hl-tickers/releases/download/v0.1.0/hl-tickers_0.1.0_darwin_arm64.tar.gz"
      sha256 "1f080ee2861f41564febb627635a9af2b99220c6b8da7a7648b5cd32a505e451"

      define_method(:install) do
        bin.install "hl-tickers"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Brayden967/hl-tickers/releases/download/v0.1.0/hl-tickers_0.1.0_linux_amd64.tar.gz"
      sha256 "8f9bf1c2f8c086b58068e59e1f7273546700e7580bec376ae1ab96bdc48fcf80"
      define_method(:install) do
        bin.install "hl-tickers"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Brayden967/hl-tickers/releases/download/v0.1.0/hl-tickers_0.1.0_linux_arm64.tar.gz"
      sha256 "7b938458bfbc65850bbbb1b765090ce3e9ed2651ed96a8d26e33ac866502eb02"
      define_method(:install) do
        bin.install "hl-tickers"
      end
    end
  end

  test do
    system "#{bin}/hl-tickers", "--version"
  end
end
